// <auto-generated />
namespace Archwyvern.Nxml.Tags
{
    [System.Xml.Serialization.XmlRoot(ElementName = "FontFile", Namespace = "http://archwyvern.com/xsd/nxml")]
    public class FontFileTag : Archwyvern.Nxml.BaseTag, Archwyvern.Nxml.IResourceTag
    {
#nullable enable
        public static class ElementProperty
        {
        }

        // Simple Attributes
        [System.Xml.Serialization.XmlAttribute(AttributeName = "GenerateMipmaps")] public string _Surrogate_Attribute_GenerateMipmaps {
            get => GenerateMipmaps != null ? ((System.Boolean)GenerateMipmaps).ToString() : "";
            set { if (value != "") { GenerateMipmaps = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.GenerateMipmaps")] public string _Surrogate_Element_GenerateMipmaps {
            get => GenerateMipmaps != null ? ((System.Boolean)GenerateMipmaps).ToString() : "";
            set { if (value != "") { GenerateMipmaps = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Boolean? GenerateMipmaps { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "Antialiasing")] public string _Surrogate_Attribute_Antialiasing {
            get => Antialiasing != null ? ((Godot.TextServer.FontAntialiasing)Antialiasing).ToString() : "";
            set { if (value != "") { Antialiasing = System.Enum.Parse<Godot.TextServer.FontAntialiasing>(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.Antialiasing")] public string _Surrogate_Element_Antialiasing {
            get => Antialiasing != null ? ((Godot.TextServer.FontAntialiasing)Antialiasing).ToString() : "";
            set { if (value != "") { Antialiasing = System.Enum.Parse<Godot.TextServer.FontAntialiasing>(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public Godot.TextServer.FontAntialiasing? Antialiasing { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "FontName")] public string _Surrogate_Attribute_FontName {
            get => FontName != null ? ((System.String)FontName).ToString() : "";
            set { if (value != "") { FontName = value; } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.FontName")] public string _Surrogate_Element_FontName {
            get => FontName != null ? ((System.String)FontName).ToString() : "";
            set { if (value != "") { FontName = value; } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.String? FontName { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "StyleName")] public string _Surrogate_Attribute_StyleName {
            get => StyleName != null ? ((System.String)StyleName).ToString() : "";
            set { if (value != "") { StyleName = value; } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.StyleName")] public string _Surrogate_Element_StyleName {
            get => StyleName != null ? ((System.String)StyleName).ToString() : "";
            set { if (value != "") { StyleName = value; } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.String? StyleName { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "FontStyle")] public string _Surrogate_Attribute_FontStyle {
            get => FontStyle != null ? ((Godot.TextServer.FontStyle)FontStyle).ToString() : "";
            set { if (value != "") { FontStyle = System.Enum.Parse<Godot.TextServer.FontStyle>(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.FontStyle")] public string _Surrogate_Element_FontStyle {
            get => FontStyle != null ? ((Godot.TextServer.FontStyle)FontStyle).ToString() : "";
            set { if (value != "") { FontStyle = System.Enum.Parse<Godot.TextServer.FontStyle>(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public Godot.TextServer.FontStyle? FontStyle { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "FontWeight")] public string _Surrogate_Attribute_FontWeight {
            get => FontWeight != null ? ((System.Int32)FontWeight).ToString() : "";
            set { if (value != "") { FontWeight = System.Int32.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.FontWeight")] public string _Surrogate_Element_FontWeight {
            get => FontWeight != null ? ((System.Int32)FontWeight).ToString() : "";
            set { if (value != "") { FontWeight = System.Int32.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Int32? FontWeight { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "FontStretch")] public string _Surrogate_Attribute_FontStretch {
            get => FontStretch != null ? ((System.Int32)FontStretch).ToString() : "";
            set { if (value != "") { FontStretch = System.Int32.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.FontStretch")] public string _Surrogate_Element_FontStretch {
            get => FontStretch != null ? ((System.Int32)FontStretch).ToString() : "";
            set { if (value != "") { FontStretch = System.Int32.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Int32? FontStretch { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "SubpixelPositioning")] public string _Surrogate_Attribute_SubpixelPositioning {
            get => SubpixelPositioning != null ? ((Godot.TextServer.SubpixelPositioning)SubpixelPositioning).ToString() : "";
            set { if (value != "") { SubpixelPositioning = System.Enum.Parse<Godot.TextServer.SubpixelPositioning>(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.SubpixelPositioning")] public string _Surrogate_Element_SubpixelPositioning {
            get => SubpixelPositioning != null ? ((Godot.TextServer.SubpixelPositioning)SubpixelPositioning).ToString() : "";
            set { if (value != "") { SubpixelPositioning = System.Enum.Parse<Godot.TextServer.SubpixelPositioning>(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public Godot.TextServer.SubpixelPositioning? SubpixelPositioning { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "MultichannelSignedDistanceField")] public string _Surrogate_Attribute_MultichannelSignedDistanceField {
            get => MultichannelSignedDistanceField != null ? ((System.Boolean)MultichannelSignedDistanceField).ToString() : "";
            set { if (value != "") { MultichannelSignedDistanceField = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.MultichannelSignedDistanceField")] public string _Surrogate_Element_MultichannelSignedDistanceField {
            get => MultichannelSignedDistanceField != null ? ((System.Boolean)MultichannelSignedDistanceField).ToString() : "";
            set { if (value != "") { MultichannelSignedDistanceField = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Boolean? MultichannelSignedDistanceField { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "MsdfPixelRange")] public string _Surrogate_Attribute_MsdfPixelRange {
            get => MsdfPixelRange != null ? ((System.Int32)MsdfPixelRange).ToString() : "";
            set { if (value != "") { MsdfPixelRange = System.Int32.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.MsdfPixelRange")] public string _Surrogate_Element_MsdfPixelRange {
            get => MsdfPixelRange != null ? ((System.Int32)MsdfPixelRange).ToString() : "";
            set { if (value != "") { MsdfPixelRange = System.Int32.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Int32? MsdfPixelRange { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "MsdfSize")] public string _Surrogate_Attribute_MsdfSize {
            get => MsdfSize != null ? ((System.Int32)MsdfSize).ToString() : "";
            set { if (value != "") { MsdfSize = System.Int32.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.MsdfSize")] public string _Surrogate_Element_MsdfSize {
            get => MsdfSize != null ? ((System.Int32)MsdfSize).ToString() : "";
            set { if (value != "") { MsdfSize = System.Int32.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Int32? MsdfSize { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "AllowSystemFallback")] public string _Surrogate_Attribute_AllowSystemFallback {
            get => AllowSystemFallback != null ? ((System.Boolean)AllowSystemFallback).ToString() : "";
            set { if (value != "") { AllowSystemFallback = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.AllowSystemFallback")] public string _Surrogate_Element_AllowSystemFallback {
            get => AllowSystemFallback != null ? ((System.Boolean)AllowSystemFallback).ToString() : "";
            set { if (value != "") { AllowSystemFallback = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Boolean? AllowSystemFallback { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "ForceAutohinter")] public string _Surrogate_Attribute_ForceAutohinter {
            get => ForceAutohinter != null ? ((System.Boolean)ForceAutohinter).ToString() : "";
            set { if (value != "") { ForceAutohinter = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.ForceAutohinter")] public string _Surrogate_Element_ForceAutohinter {
            get => ForceAutohinter != null ? ((System.Boolean)ForceAutohinter).ToString() : "";
            set { if (value != "") { ForceAutohinter = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Boolean? ForceAutohinter { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "Hinting")] public string _Surrogate_Attribute_Hinting {
            get => Hinting != null ? ((Godot.TextServer.Hinting)Hinting).ToString() : "";
            set { if (value != "") { Hinting = System.Enum.Parse<Godot.TextServer.Hinting>(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.Hinting")] public string _Surrogate_Element_Hinting {
            get => Hinting != null ? ((Godot.TextServer.Hinting)Hinting).ToString() : "";
            set { if (value != "") { Hinting = System.Enum.Parse<Godot.TextServer.Hinting>(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public Godot.TextServer.Hinting? Hinting { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "Oversampling")] public string _Surrogate_Attribute_Oversampling {
            get => Oversampling != null ? ((System.Single)Oversampling).ToString() : "";
            set { if (value != "") { Oversampling = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.Oversampling")] public string _Surrogate_Element_Oversampling {
            get => Oversampling != null ? ((System.Single)Oversampling).ToString() : "";
            set { if (value != "") { Oversampling = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Single? Oversampling { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "FixedSize")] public string _Surrogate_Attribute_FixedSize {
            get => FixedSize != null ? ((System.Int32)FixedSize).ToString() : "";
            set { if (value != "") { FixedSize = System.Int32.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.FixedSize")] public string _Surrogate_Element_FixedSize {
            get => FixedSize != null ? ((System.Int32)FixedSize).ToString() : "";
            set { if (value != "") { FixedSize = System.Int32.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Int32? FixedSize { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "ResourceLocalToScene")] public string _Surrogate_Attribute_ResourceLocalToScene {
            get => ResourceLocalToScene != null ? ((System.Boolean)ResourceLocalToScene).ToString() : "";
            set { if (value != "") { ResourceLocalToScene = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.ResourceLocalToScene")] public string _Surrogate_Element_ResourceLocalToScene {
            get => ResourceLocalToScene != null ? ((System.Boolean)ResourceLocalToScene).ToString() : "";
            set { if (value != "") { ResourceLocalToScene = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Boolean? ResourceLocalToScene { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "ResourcePath")] public string _Surrogate_Attribute_ResourcePath {
            get => ResourcePath != null ? ((System.String)ResourcePath).ToString() : "";
            set { if (value != "") { ResourcePath = value; } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.ResourcePath")] public string _Surrogate_Element_ResourcePath {
            get => ResourcePath != null ? ((System.String)ResourcePath).ToString() : "";
            set { if (value != "") { ResourcePath = value; } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.String? ResourcePath { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "ResourceName")] public string _Surrogate_Attribute_ResourceName {
            get => ResourceName != null ? ((System.String)ResourceName).ToString() : "";
            set { if (value != "") { ResourceName = value; } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "FontFile.ResourceName")] public string _Surrogate_Element_ResourceName {
            get => ResourceName != null ? ((System.String)ResourceName).ToString() : "";
            set { if (value != "") { ResourceName = value; } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.String? ResourceName { get; set; }
#nullable disable

        // Overloaded Attributes

        internal override Godot.GodotObject CreateObject(Godot.GodotObject alt = null)
        {
            if (alt != null && alt is not Godot.FontFile) return alt;
            var obj = (Godot.FontFile)alt ?? new Godot.FontFile();

            // Attributes
            if (GenerateMipmaps != null) obj.GenerateMipmaps = (System.Boolean)GenerateMipmaps;
            if (Antialiasing != null) obj.Antialiasing = (Godot.TextServer.FontAntialiasing)Antialiasing;
            if (FontName != null) obj.FontName = (System.String)FontName;
            if (StyleName != null) obj.StyleName = (System.String)StyleName;
            if (FontStyle != null) obj.FontStyle = (Godot.TextServer.FontStyle)FontStyle;
            if (FontWeight != null) obj.FontWeight = (System.Int32)FontWeight;
            if (FontStretch != null) obj.FontStretch = (System.Int32)FontStretch;
            if (SubpixelPositioning != null) obj.SubpixelPositioning = (Godot.TextServer.SubpixelPositioning)SubpixelPositioning;
            if (MultichannelSignedDistanceField != null) obj.MultichannelSignedDistanceField = (System.Boolean)MultichannelSignedDistanceField;
            if (MsdfPixelRange != null) obj.MsdfPixelRange = (System.Int32)MsdfPixelRange;
            if (MsdfSize != null) obj.MsdfSize = (System.Int32)MsdfSize;
            if (AllowSystemFallback != null) obj.AllowSystemFallback = (System.Boolean)AllowSystemFallback;
            if (ForceAutohinter != null) obj.ForceAutohinter = (System.Boolean)ForceAutohinter;
            if (Hinting != null) obj.Hinting = (Godot.TextServer.Hinting)Hinting;
            if (Oversampling != null) obj.Oversampling = (System.Single)Oversampling;
            if (FixedSize != null) obj.FixedSize = (System.Int32)FixedSize;
            if (ResourceLocalToScene != null) obj.ResourceLocalToScene = (System.Boolean)ResourceLocalToScene;
            if (ResourcePath != null) obj.ResourcePath = (System.String)ResourcePath;
            if (ResourceName != null) obj.ResourceName = (System.String)ResourceName;
            // Overloaded Attributes
            // Elements

            return obj;
        }
    }
}
