// <auto-generated />
namespace Archwyvern.Nxml.Tags
{
    [System.Xml.Serialization.XmlRoot(ElementName = "PhysicalSkyMaterial", Namespace = "http://archwyvern.com/xsd/nxml")]
    public class PhysicalSkyMaterialTag : Archwyvern.Nxml.BaseTag, Archwyvern.Nxml.IResourceTag
    {
#nullable enable
        public static class ElementProperty
        {
            [System.Xml.Serialization.XmlType(TypeName = "PhysicalSkyMaterial.ElementProperty.NightSky")] public class NightSky
            {
                [System.Xml.Serialization.XmlElement(ElementName = "AnimatedTexture", Type = typeof(AnimatedTextureTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "AtlasTexture", Type = typeof(AtlasTextureTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "CameraTexture", Type = typeof(CameraTextureTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "CanvasTexture", Type = typeof(CanvasTextureTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "CompressedTexture2D", Type = typeof(CompressedTexture2DTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "CurveTexture", Type = typeof(CurveTextureTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "CurveXyzTexture", Type = typeof(CurveXyzTextureTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "GradientTexture1D", Type = typeof(GradientTexture1DTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "GradientTexture2D", Type = typeof(GradientTexture2DTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "ImageTexture", Type = typeof(ImageTextureTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "MeshTexture", Type = typeof(MeshTextureTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "NoiseTexture2D", Type = typeof(NoiseTexture2DTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "PlaceholderTexture2D", Type = typeof(PlaceholderTexture2DTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "PortableCompressedTexture2D", Type = typeof(PortableCompressedTexture2DTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "Texture2D", Type = typeof(Texture2DTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "ViewportTexture", Type = typeof(ViewportTextureTag))]
                public Archwyvern.Nxml.BaseTag? Value;
            }

            [System.Xml.Serialization.XmlType(TypeName = "PhysicalSkyMaterial.ElementProperty.NextPass")] public class NextPass
            {
                [System.Xml.Serialization.XmlElement(ElementName = "CanvasItemMaterial", Type = typeof(CanvasItemMaterialTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "FogMaterial", Type = typeof(FogMaterialTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "Material", Type = typeof(MaterialTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "OrmMaterial3D", Type = typeof(OrmMaterial3DTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "PanoramaSkyMaterial", Type = typeof(PanoramaSkyMaterialTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "ParticleProcessMaterial", Type = typeof(ParticleProcessMaterialTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial", Type = typeof(PhysicalSkyMaterialTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "PlaceholderMaterial", Type = typeof(PlaceholderMaterialTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "ProceduralSkyMaterial", Type = typeof(ProceduralSkyMaterialTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "ShaderMaterial", Type = typeof(ShaderMaterialTag))]
                [System.Xml.Serialization.XmlElement(ElementName = "StandardMaterial3D", Type = typeof(StandardMaterial3DTag))]
                public Archwyvern.Nxml.BaseTag? Value;
            }

        }

        [System.Xml.Serialization.XmlIgnore] public BaseTag? NightSky => _Surrogate_Element_NightSky?.Value;
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.NightSky")] public PhysicalSkyMaterialTag.ElementProperty.NightSky? _Surrogate_Element_NightSky;

        [System.Xml.Serialization.XmlIgnore] public BaseTag? NextPass => _Surrogate_Element_NextPass?.Value;
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.NextPass")] public PhysicalSkyMaterialTag.ElementProperty.NextPass? _Surrogate_Element_NextPass;

        // Simple Attributes
        [System.Xml.Serialization.XmlAttribute(AttributeName = "RayleighCoefficient")] public string _Surrogate_Attribute_RayleighCoefficient {
            get => RayleighCoefficient != null ? ((System.Single)RayleighCoefficient).ToString() : "";
            set { if (value != "") { RayleighCoefficient = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.RayleighCoefficient")] public string _Surrogate_Element_RayleighCoefficient {
            get => RayleighCoefficient != null ? ((System.Single)RayleighCoefficient).ToString() : "";
            set { if (value != "") { RayleighCoefficient = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Single? RayleighCoefficient { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "MieCoefficient")] public string _Surrogate_Attribute_MieCoefficient {
            get => MieCoefficient != null ? ((System.Single)MieCoefficient).ToString() : "";
            set { if (value != "") { MieCoefficient = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.MieCoefficient")] public string _Surrogate_Element_MieCoefficient {
            get => MieCoefficient != null ? ((System.Single)MieCoefficient).ToString() : "";
            set { if (value != "") { MieCoefficient = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Single? MieCoefficient { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "MieEccentricity")] public string _Surrogate_Attribute_MieEccentricity {
            get => MieEccentricity != null ? ((System.Single)MieEccentricity).ToString() : "";
            set { if (value != "") { MieEccentricity = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.MieEccentricity")] public string _Surrogate_Element_MieEccentricity {
            get => MieEccentricity != null ? ((System.Single)MieEccentricity).ToString() : "";
            set { if (value != "") { MieEccentricity = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Single? MieEccentricity { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "Turbidity")] public string _Surrogate_Attribute_Turbidity {
            get => Turbidity != null ? ((System.Single)Turbidity).ToString() : "";
            set { if (value != "") { Turbidity = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.Turbidity")] public string _Surrogate_Element_Turbidity {
            get => Turbidity != null ? ((System.Single)Turbidity).ToString() : "";
            set { if (value != "") { Turbidity = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Single? Turbidity { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "SunDiskScale")] public string _Surrogate_Attribute_SunDiskScale {
            get => SunDiskScale != null ? ((System.Single)SunDiskScale).ToString() : "";
            set { if (value != "") { SunDiskScale = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.SunDiskScale")] public string _Surrogate_Element_SunDiskScale {
            get => SunDiskScale != null ? ((System.Single)SunDiskScale).ToString() : "";
            set { if (value != "") { SunDiskScale = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Single? SunDiskScale { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "EnergyMultiplier")] public string _Surrogate_Attribute_EnergyMultiplier {
            get => EnergyMultiplier != null ? ((System.Single)EnergyMultiplier).ToString() : "";
            set { if (value != "") { EnergyMultiplier = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.EnergyMultiplier")] public string _Surrogate_Element_EnergyMultiplier {
            get => EnergyMultiplier != null ? ((System.Single)EnergyMultiplier).ToString() : "";
            set { if (value != "") { EnergyMultiplier = System.Single.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Single? EnergyMultiplier { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "UseDebanding")] public string _Surrogate_Attribute_UseDebanding {
            get => UseDebanding != null ? ((System.Boolean)UseDebanding).ToString() : "";
            set { if (value != "") { UseDebanding = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.UseDebanding")] public string _Surrogate_Element_UseDebanding {
            get => UseDebanding != null ? ((System.Boolean)UseDebanding).ToString() : "";
            set { if (value != "") { UseDebanding = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Boolean? UseDebanding { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "RenderPriority")] public string _Surrogate_Attribute_RenderPriority {
            get => RenderPriority != null ? ((System.Int32)RenderPriority).ToString() : "";
            set { if (value != "") { RenderPriority = System.Int32.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.RenderPriority")] public string _Surrogate_Element_RenderPriority {
            get => RenderPriority != null ? ((System.Int32)RenderPriority).ToString() : "";
            set { if (value != "") { RenderPriority = System.Int32.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Int32? RenderPriority { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "ResourceLocalToScene")] public string _Surrogate_Attribute_ResourceLocalToScene {
            get => ResourceLocalToScene != null ? ((System.Boolean)ResourceLocalToScene).ToString() : "";
            set { if (value != "") { ResourceLocalToScene = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.ResourceLocalToScene")] public string _Surrogate_Element_ResourceLocalToScene {
            get => ResourceLocalToScene != null ? ((System.Boolean)ResourceLocalToScene).ToString() : "";
            set { if (value != "") { ResourceLocalToScene = System.Boolean.Parse(value); } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.Boolean? ResourceLocalToScene { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "ResourcePath")] public string _Surrogate_Attribute_ResourcePath {
            get => ResourcePath != null ? ((System.String)ResourcePath).ToString() : "";
            set { if (value != "") { ResourcePath = value; } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.ResourcePath")] public string _Surrogate_Element_ResourcePath {
            get => ResourcePath != null ? ((System.String)ResourcePath).ToString() : "";
            set { if (value != "") { ResourcePath = value; } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.String? ResourcePath { get; set; }
        [System.Xml.Serialization.XmlAttribute(AttributeName = "ResourceName")] public string _Surrogate_Attribute_ResourceName {
            get => ResourceName != null ? ((System.String)ResourceName).ToString() : "";
            set { if (value != "") { ResourceName = value; } }
        }
        [System.Xml.Serialization.XmlElement(ElementName = "PhysicalSkyMaterial.ResourceName")] public string _Surrogate_Element_ResourceName {
            get => ResourceName != null ? ((System.String)ResourceName).ToString() : "";
            set { if (value != "") { ResourceName = value; } }
        }
        [System.Xml.Serialization.XmlIgnore] public System.String? ResourceName { get; set; }
#nullable disable

        // Overloaded Attributes
        [System.Xml.Serialization.XmlAttribute(AttributeName = "RayleighColor")] public string _Surrogate_RayleighColor {
            get => RayleighColor != null ? ((Archwyvern.Nxml.Translators.Color)RayleighColor).ToString() : "";
            set => RayleighColor = value != "" ? value : null;
        }
        [System.Xml.Serialization.XmlIgnore] public Archwyvern.Nxml.Translators.Color? RayleighColor;
        [System.Xml.Serialization.XmlAttribute(AttributeName = "MieColor")] public string _Surrogate_MieColor {
            get => MieColor != null ? ((Archwyvern.Nxml.Translators.Color)MieColor).ToString() : "";
            set => MieColor = value != "" ? value : null;
        }
        [System.Xml.Serialization.XmlIgnore] public Archwyvern.Nxml.Translators.Color? MieColor;
        [System.Xml.Serialization.XmlAttribute(AttributeName = "GroundColor")] public string _Surrogate_GroundColor {
            get => GroundColor != null ? ((Archwyvern.Nxml.Translators.Color)GroundColor).ToString() : "";
            set => GroundColor = value != "" ? value : null;
        }
        [System.Xml.Serialization.XmlIgnore] public Archwyvern.Nxml.Translators.Color? GroundColor;

        internal override Godot.GodotObject CreateObject(Godot.GodotObject alt = null)
        {
            if (alt != null && alt is not Godot.PhysicalSkyMaterial) return alt;
            var obj = (Godot.PhysicalSkyMaterial)alt ?? new Godot.PhysicalSkyMaterial();

            // Attributes
            if (RayleighCoefficient != null) obj.RayleighCoefficient = (System.Single)RayleighCoefficient;
            if (MieCoefficient != null) obj.MieCoefficient = (System.Single)MieCoefficient;
            if (MieEccentricity != null) obj.MieEccentricity = (System.Single)MieEccentricity;
            if (Turbidity != null) obj.Turbidity = (System.Single)Turbidity;
            if (SunDiskScale != null) obj.SunDiskScale = (System.Single)SunDiskScale;
            if (EnergyMultiplier != null) obj.EnergyMultiplier = (System.Single)EnergyMultiplier;
            if (UseDebanding != null) obj.UseDebanding = (System.Boolean)UseDebanding;
            if (RenderPriority != null) obj.RenderPriority = (System.Int32)RenderPriority;
            if (ResourceLocalToScene != null) obj.ResourceLocalToScene = (System.Boolean)ResourceLocalToScene;
            if (ResourcePath != null) obj.ResourcePath = (System.String)ResourcePath;
            if (ResourceName != null) obj.ResourceName = (System.String)ResourceName;
            // Overloaded Attributes
            if (RayleighColor != null) obj.RayleighColor = (Archwyvern.Nxml.Translators.Color)RayleighColor;
            if (MieColor != null) obj.MieColor = (Archwyvern.Nxml.Translators.Color)MieColor;
            if (GroundColor != null) obj.GroundColor = (Archwyvern.Nxml.Translators.Color)GroundColor;
            // Elements
            if (NightSky != null) {
                if (((IResourceTag)NightSky).ResourcePath != null) {
                    obj.NightSky = (Godot.Texture2D)NightSky.Generate(Godot.GD.Load<Godot.Texture2D>(((IResourceTag)NightSky).ResourcePath));
                } else {
                    obj.NightSky = (Godot.Texture2D)NightSky.Generate();
                }
            }
            if (NextPass != null) {
                if (((IResourceTag)NextPass).ResourcePath != null) {
                    obj.NextPass = (Godot.Material)NextPass.Generate(Godot.GD.Load<Godot.Material>(((IResourceTag)NextPass).ResourcePath));
                } else {
                    obj.NextPass = (Godot.Material)NextPass.Generate();
                }
            }

            return obj;
        }
    }
}
